export default {
  README: "Getting Started",
  setup: "Setup",
  chat: "Chat Orchestration",
  messages: "Sending Messages",
  conversations: "Conversation Management",
  streaming: "Streaming Subscriptions",
  thinking: "Thinking Mode",
  memory: "Memory Retrieval",
  vault: "Memory Vault",
  tools: "Managing Tools",
  "display-tools": "Display Tools",
  "interactive-tools": "Interactive Tools",
  projects: "Projects",
  backup: "Cloud Backup",
  models: "Fetching Models",
  ocr: "Extracting Text from Images",
  notion: "Notion Integration",
};
