import type { Metadata } from "next";
import { Geist, Geist_Mono, Jost } from "next/font/google";
import "./globals.css";
import { PrivyAuthProvider, DatabaseProvider, GoogleAuthProvider, BackupAuthProvider } from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const jost = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              try {
                var theme = localStorage.getItem('app_theme');
                if (theme && theme !== 'light') {
                  document.documentElement.classList.add('theme-' + theme);
                }
              } catch (e) {}
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${jost.variable} antialiased`}
      >
        <PrivyAuthProvider>
          <DatabaseProvider>
            <BackupAuthProvider>
              <GoogleAuthProvider>{children}</GoogleAuthProvider>
            </BackupAuthProvider>
          </DatabaseProvider>
        </PrivyAuthProvider>
      </body>
    </html>
  );
}
